TrashCollector2/Models/Pickup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TrashCollector2.Models
{
    public class Pickup
    {
        [Key]
        public int ID { get; set; }
        public DateTime PickupDate { get; set; }

        public int CustomerID { get; set; }
        [ForeignKey("CustomerID")]
        public virtual Customer Customer { get; set; }

        public int? WorkerID { get; set; }
        [ForeignKey("WorkerID")]
        public virtual Worker Worker { get; set; }

        public int Charge { get; set; }
        public bool Complete { get; set; }
        public bool Suspended { get; set; }
        public DateTime? SuspensionDate { get; set; }
        public bool OneTime { get; set; }
    }
}

TrashCollector2/Controllers/PickupsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrashCollector2.Models;

namespace TrashCollector2.Controllers
{
    public class PickupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult CustomerPickups()
        {
            string userID = User.Identity.GetUserId();
            var customer = db.Customers.Where(c => c.UserID == userID).FirstOrDefault();
            var pickups = db.Pickups.Where(p => p.CustomerID == customer.ID && p.Complete == false);
            return View(pickups.ToList());
        }

        public ActionResult CompletePickup(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pickup pickup = db.Pickups.Find(id);
            if (pickup == null)
            {
                return HttpNotFound();
            }
            pickup.Complete = true;
            pickup.Customer.Balance += pickup.Charge;
            var newpickup = new Pickup();
            newpickup.CustomerID = pickup.CustomerID;
            newpickup.Customer = pickup.Customer;
            var OneWeek = new System.TimeSpan(7, 0, 0, 0);
            newpickup.PickupDate = pickup.PickupDate.Add(OneWeek);
            if (pickup.Suspended == false && pickup.OneTime == false)
            {
                db.Pickups.Add(newpickup);
            }
            db.SaveChanges();
            return View(pickup);
        }

        public ActionResult SuspendPickup(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pickup pickup = db.Pickups.Find(id);
            if (pickup == null)
            {
                return HttpNotFound();
            }
            
            pickup.PickupDate = pickup.SuspensionDate ?? pickup.PickupDate;
            pickup.SuspensionDate = null;
            return View(pickup);
        }
        public ActionResult SearchPickups(string selectedDay)
        {
           
            string userID = User.Identity.GetUserId();
            var user = db.Users.Where(u => u.Id == userID).FirstOrDefault();
            var worker = db.Workers.Where(c => c.UserID == user.Id).FirstOrDefault();
             var pickups = db.Pickups.Where(p => p.Complete == false && p.Customer.Address.ZipCode == worker.Address.ZipCode);
            switch (selectedDay)
            {
                case "monday":
                    pickups = db.Pickups.ToList().Where(p => p.PickupDate.DayOfWeek.ToString().ToLower() == "monday").AsQueryable();
                    break;
                case "tuesday":
                    pickups = pickups.ToList().Where(p => p.PickupDate.DayOfWeek.ToString().ToLower() == "tuesday").AsQueryable();
                    break;
                case "wednesday":
                    pickups = pickups.ToList().Where(p => p.PickupDate.DayOfWeek.ToString().ToLower() == "wednesday").AsQueryable();
                    break;
                case "thursday":
                    pickups = pickups.ToList().Where(p => p.PickupDate.DayOfWeek.ToString().ToLower() == "thursday").AsQueryable();
                    break;
                case "friday":
                    pickups = pickups.ToList().Where(p => p.PickupDate.DayOfWeek.ToString().ToLower() == "friday").AsQueryable();
                    break;
                case "saturday":
                    pickups = pickups.ToList().Where(p => p.PickupDate.DayOfWeek.ToString().ToLower() == "saturday").AsQueryable();
                    break;
                case "sunday":
                    pickups = pickups.ToList().Where(p => p.PickupDate.DayOfWeek.ToString().ToLower() == "sunday").AsQueryable();
                    break;
                default:
                    pickups = pickups.Where(p => p.PickupDate == DateTime.Now);
                    break;
            }

            return View(pickups.ToList());
        }

        // GET: Pickups
        public ActionResult Index()
        {
            var pickups = db.Pickups.Include(p => p.Customer).Include(p => p.Worker);
            return View(pickups.ToList());
        }

        // GET: Pickups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pickup pickup = db.Pickups.Find(id);
            if (pickup == null)
            {
                return HttpNotFound();
            }
            return View(pickup);
        }

        // GET: Pickups/Create
        public ActionResult Create()
        {
            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName");
            ViewBag.WorkerID = new SelectList(db.Workers, "ID", "Username");
            return View();
        }

        // POST: Pickups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,PickupDate,CustomerID,WorkerID,Charge,Complete,Suspended,SuspensionDate,OneTime")] Pickup pickup)
        {
            if (ModelState.IsValid)
            {
                string userID = User.Identity.GetUserId();
                var customer = db.Customers.Where(c => c.UserID == userID).FirstOrDefault();
                pickup.CustomerID = customer.ID;
                pickup.Charge = 5;
                db.Pickups.Add(pickup);
                db.SaveChanges();
                return RedirectToAction("CustomerPickups");
            }

            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName", pickup.CustomerID);
            ViewBag.WorkerID = new SelectList(db.Workers, "ID", "Username", pickup.WorkerID);
            return View(pickup);
        }

        // GET: Pickups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pickup pickup = db.Pickups.Find(id);
            if (pickup == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName", pickup.CustomerID);
            ViewBag.WorkerID = new SelectList(db.Workers, "ID", "Username", pickup.WorkerID);
            return View(pickup);
        }

        // POST: Pickups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,PickupDate,CustomerID,WorkerID,Charge,Complete,Suspended,SuspensionDate,OneTime")] Pickup pickup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pickup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName", pickup.CustomerID);
            ViewBag.WorkerID = new SelectList(db.Workers, "ID", "Username", pickup.WorkerID);
            return View(pickup);
        }

        // GET: Pickups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pickup pickup = db.Pickups.Find(id);
            if (pickup == null)
            {
                return HttpNotFound();
            }
            return View(pickup);
        }

        // POST: Pickups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pickup pickup = db.Pickups.Find(id);
            db.Pickups.Remove(pickup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrashCollector2/Controllers/WorkersController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrashCollector2.Models;

namespace TrashCollector2.Controllers
{
    public class WorkersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult WorkerHome()
        {
            string userID = User.Identity.GetUserId();
            var user = db.Users.Where(u => u.Id == userID).FirstOrDefault();
            var worker = db.Workers.Where(c => c.UserID == user.Id).FirstOrDefault();
            var pickups = db.Pickups.Where(p => p.Complete == false && p.Customer.Address.ZipCode == worker.Address.ZipCode && p.PickupDate == DateTime.Today);
            return View(pickups.ToList());

        }
        // GET: Workers
        public ActionResult Index()
        {
            var workers = db.Workers.Include(w => w.Address);
            return View(workers.ToList());
        }

        // GET: Workers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = db.Workers.Find(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }

        // GET: Workers/Create
        public ActionResult Create()
        {
            ViewBag.AddressID = new SelectList(db.Addresses, "ID", "StreetAddressLine1");
            return View();
        }

        // POST: Workers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Username,AddressID,UserID")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                worker.UserID = User.Identity.GetUserId();
                db.Workers.Add(worker);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AddressID = new SelectList(db.Addresses, "ID", "StreetAddressLine1", worker.AddressID);
            return View(worker);
        }

        // GET: Workers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = db.Workers.Find(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            ViewBag.AddressID = new SelectList(db.Addresses, "ID", "StreetAddressLine1", worker.AddressID);
            return View(worker);
        }

        // POST: Workers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Username,AddressID,UserID")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(worker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AddressID = new SelectList(db.Addresses, "ID", "StreetAddressLine1", worker.AddressID);
            return View(worker);
        }

        // GET: Workers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = db.Workers.Find(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }

        // POST: Workers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Worker worker = db.Workers.Find(id);
            db.Workers.Remove(worker);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrashCollector2/Views/Pickups/CompletePickup.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model TrashCollector2.Models.Pickup

<h1>Pickup Completed</h1>

<dt>
    @Html.DisplayNameFor(model => model.Customer.FirstName)
</dt>

<dd>
    @Html.DisplayFor(model => model.Customer.FirstName)
</dd>

<dt>
    @Html.DisplayNameFor(model => model.Customer.LastName)
</dt>

<dd>
    @Html.DisplayFor(model => model.Customer.LastName)
</dd>
<dt>
    <p>Address:</p>
</dt>
<dd>
    @Html.DisplayFor(model => model.Customer.Address.StreetAddressLine1)
    @Html.DisplayFor(Model => Model.Customer.Address.StrettAddressLine2)
    @Html.DisplayFor(Model => Model.Customer.Address.City.CityName)
    @Html.DisplayFor(Model => Model.Customer.Address.State.StateName)
    @Html.DisplayFor(Model => Model.Customer.Address.ZipCode)
</dd>


<dt>
    @Html.DisplayNameFor(model => model.Complete)
</dt>

<dd>
    @Html.DisplayFor(model => model.Complete)
</dd>
@Html.ActionLink("Back to List", "WorkerHome", "Workers")

TrashCollector2/Views/Pickups/Create.cshtml
@model TrashCollector2.Models.Pickup

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pickup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PickupDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PickupDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PickupDate, "", new { @class = "text-danger" })
            </div>
        </div>

       

       
        <div class="form-group">
            @Html.LabelFor(model => model.OneTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.OneTime)
                    @Html.ValidationMessageFor(model => model.OneTime, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CustomerPickups")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrashCollector2/Views/Pickups/CustomerPickups.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<TrashCollector2.Models.Pickup>
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PickupDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OneTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Complete)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PickupDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OneTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Complete)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>

TrashCollector2/Views/Pickups/Delete.cshtml
@model TrashCollector2.Models.Pickup

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pickup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Worker.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Worker.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PickupDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PickupDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Charge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Charge)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Complete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Complete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Suspended)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Suspended)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SuspensionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SuspensionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OneTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OneTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TrashCollector2/Views/Pickups/Details.cshtml
@model TrashCollector2.Models.Pickup

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pickup</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (User.IsInRole("Worker"))
        {
            <dt>
                @Html.DisplayNameFor(model => model.Customer.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Customer.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Customer.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Customer.LastName)
            </dd>
            <dt>
                <p>Address:</p>
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Customer.Address.StreetAddressLine1)
                @Html.DisplayFor(Model => Model.Customer.Address.StrettAddressLine2)
                @Html.DisplayFor(Model => Model.Customer.Address.City.CityName)
                @Html.DisplayFor(Model => Model.Customer.Address.State.StateName)
                @Html.DisplayFor(Model => Model.Customer.Address.ZipCode)
            </dd>
        }


        <dt>
            @Html.DisplayNameFor(model => model.PickupDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PickupDate)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Complete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Complete)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.OneTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OneTime)
        </dd>
        @if (User.IsInRole("Customer"))
        {
            <H3>
                Suspend your pickups below, if you need to
            </H3>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.SuspensionDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SuspensionDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SuspensionDate, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.ActionLink("Suspend my pickup", "SuspendPickup")
        }

    </dl>
</div>




@if (User.IsInRole("Worker"))
{

    <p>@Html.ActionLink("Complete Pickup", "CompletePickup", new { id = Model.ID })</p>
    <div id="map"></div>
    <style>
        #map {
            width: 100%;
            height: 400px;
            background-color: grey;
        }
    </style>
    <body>

        <script>


            @*function codeAddress() {
                console.log("Hello world")
                var address = "313 N Plankinton Ave, Milwaukee, Wi, 53203";
                        @(Model.Customer.Address.StreetAddressLine1)+
                    @(Model.Customer.Address.StrettAddressLine2) +
                    @(Model.Customer.Address.City.CityName) +
                    @(Model.Customer.Address.State.StateName) +
                    @(Model.Customer.Address.ZipCode);
                    console.log(address);
                var geocoder = new google.maps.Geocoder("313 N Plankinton Ave, Milwaukee, Wi, 53203");
                var result = geocoder.geocode({ 'address': "313 N Plankinton Ave, Milwaukee, Wi, 53203" }, function (results, status) {
                        if (status == 'OK') {
                            map.setCenter(results[0].geometry.location);
                            var marker = new google.maps.Marker({
                                map: map,
                                position: results[0].geometry.location
                            });
                        } else {
                            alert('Geocode was not successful for the following reason: ' + status);
                        }
                    });
                    console.log(result)
                }*@

            // Initialize and add the map
            function initMap() {
                // The location of Uluru
                var address = { lat: @Model.Customer.Address.Latitude, lng: @Model.Customer.Address.Longitude };
                // The map, centered at Uluru
                var map = new google.maps.Map(
                    document.getElementById('map'), { zoom: 4, center: address });
                // The marker, positioned at Uluru
                var marker = new google.maps.Marker({ position: address, map: map });
            }
            codeAddress();
        </script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyALBFZuNCwF1ecDBWm5MOzl9C6WvxQMs6s&callback=initMap">
        </script>
    </body>
}
<p>
    @if (User.IsInRole("Customer"))
    {
        @Html.ActionLink("Back to List", "CustomerPickups")
    }
    @if (User.IsInRole("Worker"))
    {
        @Html.ActionLink("Back to List", "WorkerHome", "Workers")
    }
</p>

TrashCollector2/Views/Pickups/Index.cshtml
@model IEnumerable<TrashCollector2.Models.Pickup>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Worker.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PickupDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Charge)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Complete)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Suspended)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SuspensionDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OneTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Worker.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PickupDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Charge)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Complete)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Suspended)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SuspensionDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OneTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

TrashCollector2/Views/Pickups/SearchPickups.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<TrashCollector2.Models.Pickup>
@{
    ViewBag.Title = "Index";
}
<h2>Sort by Day</h2>
@Html.ActionLink("Monday", "SearchPickups", new { selectedDay = "monday" })
@Html.ActionLink("Tuesday", "SearchPickups", new { selectedDay = "tuesday" })
@Html.ActionLink("Wednesday", "SearchPickups", new { selectedDay = "wednesday" })
@Html.ActionLink("Thursday", "SearchPickups", new { selectedDay = "thursday" })
@Html.ActionLink("Friday", "SearchPickups", new { selectedDay = "friday" })
@Html.ActionLink("Saturday", "SearchPickups", new { selectedDay = "saturday" })
@Html.ActionLink("Sunday", "SearchPickups", new { selectedDay = "sunday" })





<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PickupDate)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Complete)
        </th>

        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PickupDate)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Complete)
            </td>


            <td>
                @Html.ActionLink("Details", "Details", "Pickups", new { id = item.ID }, null)
            </td>
        </tr>
    }
</table>